### PR TITLE
cleanup .snakemake/metadata

### PR DESCRIPTION
**Pull request by pdiakumis**
Removes a bunch of snakemake metadata files that aren't really needed on S3.

### CODE REVIEW

**Review by vladsavelyev — APPROVED** [review]
Cool! 

Thanks for changing the deprecated `::add-path`

**Comment by pdiakumis** [comment]
Don't think I can bump the version though - can you do that from your side to get it picked up by umccrise? 🙇

**Comment by vladsavelyev** [comment]
Done!

**Comment by pdiakumis** [comment]
Gah, my indentation went off a bit - can you indent that final line properly in the smk file and re-bump? What a shocker...

```
shutil.rmtree(".snakemake/metadata")
```

**Pull request merged**
